FROM golang:alpine

RUN apk update && \
    apk add git build-base && \
    rm -rf /var/cache/apk/* && \
    go get -v -d github.com/thinhle-agilityio/kubewatch && \
    cd "$GOPATH/src/github.com/thinhle-agilityio/kubewatch" && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a --installsuffix cgo --ldflags="-s" -o /kubewatch

COPY Dockerfile.run /
CMD tar -cf - -C / Dockerfile.run kubewatch
