apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubewatch
  namespace: default
  labels:
    name: kubewatch
    environment: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kubewatch
    spec:
      containers:
      - image: thienthinh/kubewatch:v0.0.3
        imagePullPolicy: Always
        name: kubewatch
        env:
        - name: KW_SLACK_WEBHOOK
          valueFrom:
            secretKeyRef:
              name: kubewatch
              key: webhook
        volumeMounts:
        - name: config-volume
          mountPath: /root
      - image: gcr.io/skippbox/kubectl:v1.3.0
        args:
          - proxy
          - "-p"
          - "8080"
        name: proxy
        imagePullPolicy: Always
      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
          name: kubewatch
